In [1]:
%matplotlib inline

import os
import sys
ai_lit_path = os.path.abspath(os.path.join(os.getcwd(), os.pardir, os.pardir, os.pardir))
print("Loading AI Lit system from path", ai_lit_path)
sys.path.append(ai_lit_path)

import numpy as np
import pandas as pd
import tensorflow as tf

from ai_lit.input.gutenberg_dataset import gb_input
from ai_lit.input.gutenberg_dataset import gb_titles_dataset
# from ai_lit.input.gutenberg_dataset import gb_full_dataset
from ai_lit.university.gutenberg import gb_title_university
# from ai_lit.university.gutenberg import gb_full_university

Loading AI Lit system from path /mnt/d/UNIV NOTES/Y4S1/DSA4199/ai-lit


2022-10-20 09:53:52.888340: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-20 09:53:52.889658: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
tf.compat.v1.flags.DEFINE_string('f','','')

dataset_wkspc = os.path.join(ai_lit_path, 'workspace', 'gb_input')
training_wkspc = os.path.join(ai_lit_path, 'workspace', 'gutenberg_title')
# training_wkspc = os.path.join(ai_lit_path, 'workspace', 'gutenberg_full')
subjects = gb_input.get_subjects(dataset_wkspc)

univ = gb_title_university.GbTitlesUniversity('checking_dataset', training_wkspc, dataset_wkspc)

In [3]:
subjects

['Science fiction',
 'Adventure stories',
 'Historical fiction',
 'Love stories',
 'Detective and mystery stories',
 'Western stories']

In [4]:
train_label, train_bodies = univ.get_training_data()
test_label, test_bodies = univ.get_evaluation_data()

2022-09-19 21:48:51.545481: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-09-19 21:48:51.545552: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-09-19 21:48:51.545598: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-52GA1L3): /proc/driver/nvidia/version does not exist
2022-09-19 21:48:51.546206: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Instructions for updating:
This is a deprecated API that should only be used in TF 1 graph mode and legacy TF 2 graph mode available through `tf.compat.v1`. In all other situations -- namely, eager mode and inside `tf.function` -- you can consume dataset elements using `for elem in dataset: ...` or by explicitly creating iterator via `iterator = iter(dataset)` and fetching its elements via `values = next(iterator)`. Furthermore, this API is not available in TF 2. During the transition from TF 1 to TF 2 you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)` to create a TF 1 graph mode style iterator for a dataset created through TF 2 APIs. Note that this should be a transient state of your code base as there are in general no guarantees about the interoperability of TF 1 and TF 2 code.


In [5]:
print(type(train_label))
print(type(train_bodies))
print(type(test_label))
print(type(test_bodies))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [6]:
train_bodies

<tf.Tensor: shape=(20, 13), dtype=int64, numpy=
array([[4457,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [4457, 1060, 3084,  718,    1,    0,    0,    0,    0,    0,    0,
           0,    0],
       [4457,  449, 3084, 2415,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [4457,  744, 3084, 2445,    1,    0,    0,    0,    0,    0,    0,
           0,    0],
       [4457, 3585, 4514, 2771,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [ 527,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [4457,  174, 3084,  718, 2222,    0,    0,    0,    0,    0,    0,
           0,    0],
       [3099, 3808, 3210,   22,   87,   99, 4398, 3084, 4457, 3294,  265,
        4457, 1751],
       [4457, 2951,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
  

In [7]:
train_label

<tf.Tensor: shape=(20, 6), dtype=int64, numpy=
array([[0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])>

In [8]:
test_bodies

<tf.Tensor: shape=(20, 12), dtype=int64, numpy=
array([[4144,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0],
       [  99,    1,    1,   88, 3121,   34, 4501,    1, 4976, 4637,  773,
         201],
       [  99, 1157, 3084, 4457,    1,   87,   99, 4258, 3084, 2999,    1,
        4539],
       [4457, 1157, 3084, 4457,    1,    0,    0,    0,    0,    0,    0,
           0],
       [   1, 2504,   87,   99, 4258, 3084,    1,    0,    0,    0,    0,
           0],
       [4457,    1,  265, 4457,    1,    0,    0,    0,    0,    0,    0,
           0],
       [   1,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0],
       [4457,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0],
       [2706,  265, 2931,    1,    0,    0,    0,    0,    0,    0,    0,
           0],
       [4457, 2753, 4908,   99, 1057,   34,  265, 3129, 4399,    0,    0,
           0],
       [   1,    0,    0,    0,    0,    0,    0,    0,    0, 

In [9]:
test_label

<tf.Tensor: shape=(20, 6), dtype=int64, numpy=
array([[0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0]])>

In [10]:
univ.vocab

['<pad>',
 '<unk>',
 '!',
 '#',
 '$',
 '%',
 '&',
 "'",
 "''",
 "'+",
 "'-",
 "'-._",
 "'-and",
 "'-bq",
 "'-it",
 "'-peculiar",
 "'-replying",
 "'-sn-b",
 "'-stay",
 "'-the-wisp",
 "'.38",
 "'.t",
 "'/",
 "'/quoth",
 "'/then",
 "'/unshit",
 "'00",
 "'03",
 "'05",
 "'06",
 "'07",
 "'08",
 "'09",
 "'10",
 "'103",
 "'11",
 "'11:30",
 "'13",
 "'13,238",
 "'14",
 "'15",
 "'16",
 "'16909",
 "'17",
 "'18",
 "'1804",
 "'1837",
 "'1850",
 "'1856",
 "'19",
 "'20",
 "'20s",
 "'21",
 "'213",
 "'22",
 "'23",
 "'24",
 "'25",
 "'258",
 "'26",
 "'27",
 "'29",
 "'31",
 "'32",
 "'32'",
 "'321",
 "'33",
 "'34",
 "'35",
 "'36",
 "'37",
 "'38",
 "'39",
 "'40",
 "'400",
 "'41",
 "'41.",
 "'42",
 "'42.",
 "'43",
 "'44",
 "'45",
 "'45._",
 "'45s",
 "'46",
 "'47",
 "'48",
 "'48-year",
 "'49",
 "'49er",
 "'50",
 "'50s",
 "'51",
 "'52",
 "'53",
 "'54",
 "'55",
 "'56",
 "'57",
 "'58",
 "'59",
 "'60",
 "'606",
 "'60s",
 "'61",
 "'62",
 "'63",
 "'630",
 "'64",
 "'64-65",
 "'65",
 "'66",
 "'668",
 "'67",
 "'68",
 "

In [11]:
train_ds = gb_titles_dataset.get_training_dataset(dataset_wkspc, len(subjects), univ.vocab)
test_ds = gb_titles_dataset.get_testing_dataset(dataset_wkspc, len(subjects), univ.vocab)

In [12]:
list(train_ds.as_numpy_iterator())[:5]

[(array([[0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 1],
         [0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 1, 0],
         [0, 1, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 1],
         [0, 1, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 1],
         [1, 0, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0],
         [1, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 1]]),
  array([[3099, 3808, 3210,   22,   87,   99, 4398, 3084, 4457, 3294,  265,
          4457, 1751,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0],
         [3143, 4457, 3196,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,

In [13]:
train_inputs, test_inputs, subjects2, vocab2 = gb_input.get_inputs(dataset_wkspc, 5000)

In [14]:
print(type(train_inputs))
print(type(test_inputs))
print(type(subjects2))
print(type(vocab2))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>


In [15]:
subjects2

['Science fiction',
 'Adventure stories',
 'Historical fiction',
 'Love stories',
 'Detective and mystery stories',
 'Western stories']

In [19]:
type(train_inputs[0])

ai_lit.input.gutenberg_dataset.gb_input.GutenbergIndex

In [21]:
print(len(train_inputs))
print(len(test_inputs))

2936
1212


In [26]:
import json

with open(os.path.join(ai_lit_path, 'workspace', 'gb_input', 'train_index_list.json')) as json_file:
    train_json = json.load(json_file)
with open(os.path.join(ai_lit_path, 'workspace', 'gb_input', 'test_index_list.json')) as json_file:
    test_json = json.load(json_file)

In [27]:
print(len(train_json))
print(len(test_json))

2936
1212


In [40]:
i = 1001
for data in train_json[1000:1100]:
    print(i, data['subjects'])
    i+=1

1001 ['Science fiction', 'Short stories']
1002 ['Western stories', 'Farm life -- Manitoba -- Fiction']
1003 ['Science fiction', 'Short stories']
1004 ['Western stories']
1005 ['Short stories', 'Chauffeurs -- Fiction', 'Detective and mystery stories']
1006 ['Love stories', 'Adventure stories', 'Mutiny -- Fiction', 'Sea stories', 'Gold mines and mining -- Fiction']
1007 ['Science fiction', 'Human-alien encounters -- Fiction']
1008 ['Western stories', 'American fiction -- 19th century']
1009 ['Western stories']
1010 ['Historical fiction', 'England -- Social life and customs -- 19th century -- Fiction', 'Great Britain -- History -- Regency, 1800-1837 -- Fiction', 'Love stories', 'Soldiers -- Fiction', 'Wessex (England) -- Fiction', 'Napoleonic Wars, 1800-1815 -- Fiction', 'Merchant mariners -- Fiction', 'Brothers -- Fiction']
1011 ['Science fiction', 'Short stories']
1012 ['Science fiction', 'Short stories']
1013 ['Extraterrestrial beings -- Fiction', 'Science fiction', 'Short stories']
10

In [44]:
i = 1001
for data in test_json[100:200]:
    print(i, data['subjects'])
    i+=1

1001 ['New Orleans (La.) -- Fiction', 'Love stories']
1002 ['Great Britain -- History -- Elizabeth, 1558-1603 -- Fiction', 'Historical fiction', 'Persecution -- England -- History -- 16th century -- Fiction', 'Catholics -- England -- History -- 16th century -- Fiction']
1003 ['Sea stories', 'Adventure stories', 'Oceania -- Fiction', 'Schooners -- Fiction']
1004 ['Dime novels', 'Love stories', 'Germany -- Fiction']
1005 ['Detective and mystery stories']
1006 ['Love stories', 'Ontario -- Fiction', 'Young women -- Fiction']
1007 ['Science fiction', 'Space ships -- Fiction', 'Manned space flight -- Fiction', 'Moon -- Fiction', 'Space flight to the moon -- Fiction']
1008 ['Burr Conspiracy, 1805-1807 -- Fiction', 'Historical fiction', 'Stateless persons -- Fiction', 'Exiles -- Fiction', 'Sea stories', 'Soldiers -- Fiction']
1009 ['Fiction', 'Detective and mystery stories']
1010 ['Women pioneers -- Fiction', 'California -- Fiction', 'Western stories']
1011 ['Western stories']
1012 ['Indians o

In [31]:
train_subjects = []
for data in train_json:
    train_subjects.extend(data['subjects'])

In [32]:
for subject in subjects:
    print(train_subjects.count(subject))

1309
494
298
377
353
295


In [34]:
test_subjects = []
for data in test_json:
    test_subjects.extend(data['subjects'])

In [35]:
for subject in subjects:
    print(test_subjects.count(subject))

539
206
109
161
156
119


In [4]:
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk import download
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score

import json

download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/kathyij74/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [20]:
dataset_wkspc = os.path.join(ai_lit_path, 'workspace', 'gb_input')
train_json_path = os.path.join(dataset_wkspc, 'train_index_list.json')
test_json_path = os.path.join(dataset_wkspc, 'test_index_list.json')

with open(train_json_path) as f:
    train_json = json.load(f)
with open(test_json_path) as f:
    test_json = json.load(f)

In [7]:
train_subjects = {}
for entry in train_json:
    train_subjects.update({entry['index']: entry['subjects']})

In [8]:
train_subjects

{'10002': ['Science fiction'],
 '10005': ['Science fiction', 'Space flight to the moon -- Fiction'],
 '10008': ['Science fiction'],
 '10046': ['Historical fiction',
  'Virginia -- History -- Colonial period, ca. 1600-1775 -- Fiction',
  'Glasgow (Scotland) -- Fiction',
  'Scottish Americans -- Virginia -- Fiction',
  'Jamestown (Va.) -- Fiction'],
 '10067': ['Fiction', 'Detective and mystery stories'],
 '10094': ['Historical fiction',
  'Biographical fiction',
  'Virginia -- History -- Colonial period, ca. 1600-1775 -- Fiction',
  'Soldiers -- Fiction',
  'Washington, George, 1732-1799 -- Fiction',
  "Braddock's Campaign, 1755 -- Fiction"],
 '10109': ['Napoleon I, Emperor of the French, 1769-1821 -- Fiction',
  'Fathers and sons -- Fiction',
  'Adventure stories',
  'Massachusetts -- Fiction'],
 '10124': ['Western stories',
  'Family -- Juvenile fiction',
  'Voyages and travels -- Juvenile fiction',
  'Young women -- Juvenile fiction',
  'Uncles -- Juvenile fiction',
  'Cousins -- Juve

In [13]:
subjects = gb_input.get_subjects(dataset_wkspc)

for key in train_subjects:
    train_subjects.update({key: list(set(train_subjects[key]).intersection(subjects))})

In [14]:
train_subjects

{'10002': ['Science fiction'],
 '10005': ['Science fiction'],
 '10008': ['Science fiction'],
 '10046': ['Historical fiction'],
 '10067': ['Detective and mystery stories'],
 '10094': ['Historical fiction'],
 '10109': ['Adventure stories'],
 '10124': ['Western stories'],
 '1014': ['Western stories'],
 '10234': ['Historical fiction'],
 '10324': ['Western stories'],
 '1033': ['Historical fiction', 'Love stories'],
 '10371': ['Detective and mystery stories'],
 '10372': ['Western stories'],
 '10391': ['Science fiction'],
 '10402': ['Adventure stories'],
 '10418': ['Love stories'],
 '10434': ['Historical fiction'],
 '10443': ['Detective and mystery stories'],
 '10452': ['Love stories'],
 '10455': ['Historical fiction'],
 '10465': ['Adventure stories'],
 '10473': ['Western stories'],
 '10476': ['Detective and mystery stories'],
 '105': ['Love stories'],
 '10509': ['Love stories'],
 '10542': ['Science fiction'],
 '10584': ['Detective and mystery stories'],
 '10585': ['Detective and mystery stor

In [15]:
more_than_one_genre = []
for key, value in train_subjects.items():
    if (len(value) > 1):
        more_than_one_genre.append(key)

In [17]:
len(more_than_one_genre)

187

In [18]:
len(train_subjects)

2936

In [19]:
for entry in more_than_one_genre:
    print(train_subjects[entry])

['Historical fiction', 'Love stories']
['Love stories', 'Western stories']
['Historical fiction', 'Love stories']
['Historical fiction', 'Western stories']
['Adventure stories', 'Love stories']
['Historical fiction', 'Western stories']
['Historical fiction', 'Love stories']
['Adventure stories', 'Science fiction']
['Love stories', 'Science fiction']
['Historical fiction', 'Western stories']
['Adventure stories', 'Love stories']
['Adventure stories', 'Love stories']
['Historical fiction', 'Western stories']
['Historical fiction', 'Love stories']
['Adventure stories', 'Historical fiction']
['Historical fiction', 'Love stories']
['Detective and mystery stories', 'Historical fiction']
['Historical fiction', 'Love stories']
['Historical fiction', 'Love stories']
['Adventure stories', 'Science fiction']
['Adventure stories', 'Love stories']
['Adventure stories', 'Detective and mystery stories']
['Adventure stories', 'Western stories']
['Adventure stories', 'Western stories']
['Historical fic

In [21]:
test_subjects = {}
for entry in test_json:
    test_subjects.update({entry['index']: entry['subjects']})
subjects = gb_input.get_subjects(dataset_wkspc)

for key in test_subjects:
    test_subjects.update({key: list(set(test_subjects[key]).intersection(subjects))})

In [22]:
test_subjects

{'10029': ['Detective and mystery stories'],
 '10066': ['Western stories'],
 '10076': ['Love stories'],
 '10082': ['Detective and mystery stories'],
 '10083': ['Detective and mystery stories'],
 '10165': ['Science fiction'],
 '10213': ['Western stories'],
 '1027': ['Western stories'],
 '1036': ['Historical fiction'],
 '10368': ['Adventure stories'],
 '10374': ['Western stories'],
 '10404': ['Western stories'],
 '10537': ['Detective and mystery stories'],
 '10575': ['Detective and mystery stories'],
 '10690': ['Adventure stories'],
 '10736': ['Adventure stories'],
 '1078': ['Historical fiction'],
 '10859': ['Love stories'],
 '10862': ['Adventure stories'],
 '11093': ['Western stories'],
 '11165': ['Love stories'],
 '112': ['Love stories'],
 '11228': ['Historical fiction'],
 '11229': ['Science fiction'],
 '11328': ['Adventure stories'],
 '11413': ['Historical fiction'],
 '11493': ['Detective and mystery stories'],
 '11501': ['Western stories'],
 '11572': ['Love stories'],
 '11602': ['Adv

In [51]:
len(test_subjects)

1212

In [23]:
more_than_one_genre_test = []
for key, value in test_subjects.items():
    if (len(value) > 1):
        more_than_one_genre_test.append(key)

In [25]:
len(more_than_one_genre_test)

72

In [26]:
for entry in more_than_one_genre_test:
    print(test_subjects[entry])

['Detective and mystery stories', 'Love stories']
['Adventure stories', 'Historical fiction']
['Adventure stories', 'Historical fiction', 'Western stories']
['Historical fiction', 'Love stories']
['Adventure stories', 'Love stories', 'Science fiction']
['Adventure stories', 'Historical fiction', 'Love stories']
['Love stories', 'Western stories']
['Detective and mystery stories', 'Western stories']
['Historical fiction', 'Love stories']
['Adventure stories', 'Historical fiction']
['Adventure stories', 'Love stories']
['Adventure stories', 'Detective and mystery stories']
['Historical fiction', 'Love stories', 'Western stories']
['Historical fiction', 'Western stories']
['Adventure stories', 'Historical fiction', 'Western stories']
['Adventure stories', 'Western stories']
['Adventure stories', 'Historical fiction']
['Adventure stories', 'Love stories']
['Adventure stories', 'Love stories']
['Adventure stories', 'Historical fiction']
['Detective and mystery stories', 'Science fiction']
[

In [27]:
for entry in more_than_one_genre:
    del train_subjects[entry]

In [28]:
train_subjects

{'10002': ['Science fiction'],
 '10005': ['Science fiction'],
 '10008': ['Science fiction'],
 '10046': ['Historical fiction'],
 '10067': ['Detective and mystery stories'],
 '10094': ['Historical fiction'],
 '10109': ['Adventure stories'],
 '10124': ['Western stories'],
 '1014': ['Western stories'],
 '10234': ['Historical fiction'],
 '10324': ['Western stories'],
 '10371': ['Detective and mystery stories'],
 '10372': ['Western stories'],
 '10391': ['Science fiction'],
 '10402': ['Adventure stories'],
 '10418': ['Love stories'],
 '10434': ['Historical fiction'],
 '10443': ['Detective and mystery stories'],
 '10452': ['Love stories'],
 '10455': ['Historical fiction'],
 '10465': ['Adventure stories'],
 '10473': ['Western stories'],
 '10476': ['Detective and mystery stories'],
 '105': ['Love stories'],
 '10509': ['Love stories'],
 '10542': ['Science fiction'],
 '10584': ['Detective and mystery stories'],
 '10585': ['Detective and mystery stories'],
 '106': ['Adventure stories'],
 '10601': [

In [31]:
double_subjects = []
double_subjects.extend(more_than_one_genre)
double_subjects.extend(more_than_one_genre_test)

In [32]:
double_subjects

['1033',
 '10932',
 '11379',
 '11534',
 '12191',
 '12270',
 '12280',
 '123',
 '1249',
 '12791',
 '13740',
 '13967',
 '14362',
 '1569',
 '16041',
 '16692',
 '1678',
 '17498',
 '17690',
 '18857',
 '18883',
 '1976',
 '19928',
 '20384',
 '20418',
 '20898',
 '21094',
 '24033',
 '25670',
 '25799',
 '26045',
 '27454',
 '27681',
 '2785',
 '27921',
 '27929',
 '28387',
 '28440',
 '28597',
 '2864',
 '29104',
 '29571',
 '30137',
 '30344',
 '30980',
 '31021',
 '31257',
 '31380',
 '31518',
 '31528',
 '31586',
 '31778',
 '32302',
 '32359',
 '32784',
 '33208',
 '33230',
 '33557',
 '33884',
 '34861',
 '34996',
 '35074',
 '35117',
 '35205',
 '35247',
 '35277',
 '35828',
 '35866',
 '36588',
 '37042',
 '37249',
 '37492',
 '38703',
 '38895',
 '39576',
 '40262',
 '403',
 '40570',
 '40800',
 '4082',
 '4097',
 '41078',
 '41089',
 '41313',
 '41314',
 '41802',
 '41822',
 '42206',
 '42389',
 '42562',
 '42740',
 '42902',
 '43235',
 '43298',
 '43301',
 '43351',
 '43838',
 '44375',
 '44455',
 '4552',
 '45582',
 '45

In [43]:
data_json = train_json.copy()
print(len(data_json))
data_json.extend(test_json.copy())
print(len(data_json))

2936
4148


In [49]:
data_json_new = []

for entry in data_json:
    if not (entry['index'] in double_subjects):
        data_json_new.append(entry)

In [50]:
len(data_json_new)

3889

In [52]:
with open('data_index.json', 'w') as f:
    json.dump(data_json_new, f)

In [53]:
with open(os.path.join(dataset_wkspc, 'data_index.json')) as f:
    data_index_json = json.load(f)

In [54]:
len(data_index_json)

3889

In [58]:
data_index_json[503]

{'index': '21513',
 'indexfile': 'Gutenberg/cache/epub/21513/pg21513.rdf',
 'title': 'the life and adventures of peter wilkins, volume 1 (of 2)',
 'author': 'paltock, robert',
 'subjects': ['Adventure stories', 'Fantasy fiction'],
 'bodyfile': 'Gutenberg/aleph.gutenberg.org/2/1/5/1/21513/21513.zip',
 'body': 'the project gutenberg ebook of life and adventures of peter wilkins, vol.\r\ni. (of ii.), by robert paltock\r\n\r\nthis ebook is for the use of anyone anywhere at no cost and with\r\nalmost no restrictions whatsoever.  you may copy it, give it away or\r\nre-use it under the terms of the project gutenberg license included\r\nwith this ebook or online at www.gutenberg.org\r\n\r\n\r\ntitle: life and adventures of peter wilkins, vol. i. (of ii.)\r\n\r\nauthor: robert paltock\r\n\r\ncommentator: a. h. bullen\r\n\r\nrelease date: may 17, 2007 [ebook #21513]\r\n\r\nlanguage: english\r\n\r\ncharacter set encoding: ascii\r\n\r\n*** start of this project gutenberg ebook adventures of peter 